apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ["sh","-c","until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;"]
      containers:
      - name: flask-app
        image: {{ .Values.flask.image }}
        ports:
        - containerPort: {{ .Values.flask.port }}
        env:
        - name: FLASK_PROJECT
          value: {{ .Values.flask.project | quote }}
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: {{ .Values.mysql.user | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.password | quote }}
        - name: MYSQL_DB
          value: {{ .Values.mysql.database | quote }}

